#mode
use_image: false
use_state: True
onscreen_render: True
task_name: "goal_tgdm_kitchen_panda" # "kitchen_one_task" "kitchen_all_task" "kitchen_one_task_allstep" "act_example"
use_wandb: false

#train
num_epochs: 20000
lr: 1.0e-5
train_batch_size: 8
val_batch_size: 8
weight_decay: 0.0001
lr_drop: 200
load_pretrain: False
use_robotic_dynamic: True
load_pretrain_robotic_dynamic: false
pretrain_robotic_dynamic_path: false
robotic_name: "panda_franka"
seed: 0
ckpt_dir: "../outputs/goal_tgdm_model/tgdm_policy"
policy_class: "TGDM"
pretrain_ckpt: ""
dataset_dir: ""
dataset_name: ""
episode_len: 0
num_episodes: 0
device: "cuda"
skip_data: null
nll_prior_train: False
load_all_episode: False

#log
plt: False
WANDB_PROJECT_NAME: 'goal_tgdm_model'
WANDB_ENTITY_NAME: 'sun1599895936'
exp_name: 'kitchen_panda_tgdm'
save_log_path: '../logs/goal_tgdm_model'
prefix_name: True

#transformer
hidden_dim: 512
dropout: 0.1
nheads: 8
dim_feedforward: 3200
enc_layers: 4
dec_layers: 7
pre_norm: true
activation: "relu"

#backbone 
lr_backbone: 1.0e-05
masks: false
backbone: resnet18
dilation: false
position_embedding: sine

# detr-vae
num_queries: 400
latent_dim: 32

# act policy
kl_weight: 10
clip_max_norm: 0.1
chunk_size: 100
temporal_agg: true

#base tgdm environment
action_dim: 9
joint_dim: 9
env_dim: 30
goal_dim: 30
endeffector_dim: 3
hl_action_dim: 3
hl_env_pos_dim: 4


# Mujoco simulator
DT: 0.02
camera_names: ['top']

#robotic_dynamic transformer
panda_franka:
  hidden_dim: 512
  dropout: 0.1
  nheads: 8
  dim_feedforward: 3200
  enc_layers: 4
  pre_norm: False
  activation: "relu"
  joint_base_xpose: [0.0, 0.0, 0.18]

#prior inference transformer
prior_inference:
  hidden_dim: 512
  dropout: 0.1
  nheads: 8
  dim_feedforward: 3200
  enc_layers: 4
  pre_norm: False
  activation: "relu"

#subtask rewritting params
goal_tgdm_kitchen_panda:
  dataset_dir: "../data/kitchen_all_data/"
  episode_len: 270
  num_episodes: 601
  num_queries: 200
  WANDB_PROJECT_NAME: 'goal_tgdm_model'
  exp_name: 'kitchen_panda_tgdm'
  env_dim: 30
  skip_data: null
  load_all_episode: true
