#mode
use_image: false
use_state: True
onscreen_render: True
task_name: "kitchen_one_task_allstep" # "kitchen_one_task" "kitchen_all_task" "kitchen_one_task_allstep" "act_example"
use_wandb: True

#train
num_epochs: 2000
lr: 1.0e-5
train_batch_size: 8
val_batch_size: 8
weight_decay: 0.0001
epochs: 300
lr_drop: 200
load_pretrain: False
seed: 0
ckpt_dir: "../outputs/imitation_model/act_policy"
policy_class: "ACT"
pretrain_ckpt: ""
dataset_dir: ""
dataset_name: ""
episode_len: 0
num_episodes: 0
device: "cuda"

#log
plt: False
WANDB_PROJECT_NAME: 'imitation_act_model'
WANDB_ENTITY_NAME: 'sun1599895936'
exp_name: 'kitchen_panda_act_one_task'
save_log_path: '../logs/imitation_act_model'
prefix_name: False

#transformer
hidden_dim: 512
dropout: 0.1
nheads: 8
dim_feedforward: 3200
enc_layers: 4
dec_layers: 7
pre_norm: true
activation: "relu"

#backbone 
lr_backbone: 1.0e-05
masks: false
backbone: resnet18
dilation: false
position_embedding: sine

# detr-vae
num_queries: 400
action_dim: 9
joint_dim: 9
env_dim: 60
latent_dim: 32

# act policy
kl_weight: 10
clip_max_norm: 0.1
chunk_size: 100
temporal_agg: true

# Mujoco simulator
DT: 0.02
camera_names: ['top']

#subtask rewritting params
kitchen_one_task:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "begin to microwave.csv"
  episode_len: 20
  num_episodes: 300
  num_queries: 20
  WANDB_PROJECT_NAME: 'imitation_act_model'
  exp_name: 'kitchen_panda_act_one_task'
kitchen_all_task:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "microwave_kettle_bottom_burner_3.csv"
  episode_len: 200
  num_episodes: 30
  num_queries: 50
  WANDB_PROJECT_NAME: 'imitation_act_model_all_task'
  exp_name: 'kitchen_panda_act_all_task'
kitchen_one_task_allstep:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "microwave_data.pkl"
  episode_len: 800
  num_episodes: 300
  num_queries: 200
  WANDB_PROJECT_NAME: 'imitation_act_model_all_step'
  exp_name: 'kitchen_panda_act_all_step'
  env_dim: 30
act_example:
  use_image: true
  use_state: false
  dataset_dir: "../data/imitation/example/"
  dataset_name: "sim_transfer_cube_scripted"
  action_dim: 14
  joint_dim: 14
  episode_len: 400
  num_episodes: 50
  WANDB_PROJECT_NAME: 'imitation_act_example'
  exp_name: 'demo_sim_transfer_cube_scripted'