#mode
use_image: false
use_state: True
onscreen_render: True
task_name: "goal_tgdm_kitchen_panda" # "kitchen_one_task" "kitchen_all_task" "kitchen_one_task_allstep" "act_example"
use_wandb: False

#train
num_epochs: 2000
lr: 1.0e-5
train_batch_size: 8
val_batch_size: 8
weight_decay: 0.0001
epochs: 300
lr_drop: 200
load_pretrain: False
seed: 0
ckpt_dir: "../outputs/imitation_model/act_policy"
policy_class: "ACT"
pretrain_ckpt: ""
dataset_dir: ""
dataset_name: ""
episode_len: 0
num_episodes: 0
device: "cuda"
skip_data: 0

#log
plt: False
WANDB_PROJECT_NAME: 'imitation_act_model'
WANDB_ENTITY_NAME: 'sun1599895936'
exp_name: 'kitchen_panda_act_one_task'
save_log_path: '../logs/imitation_act_model'
prefix_name: True

#transformer
hidden_dim: 512
dropout: 0.1
nheads: 8
dim_feedforward: 3200
enc_layers: 4
dec_layers: 7
pre_norm: false
activation: "relu"

#backbone 
lr_backbone: 1.0e-05
masks: false
backbone: resnet18
dilation: false
position_embedding: sine

# detr-vae
num_queries: 400
action_dim: 9
joint_dim: 9
env_dim: 60
latent_dim: 32

# act policy
kl_weight: 10
clip_max_norm: 0.1
chunk_size: 100
temporal_agg: true

# Mujoco simulator
env_name: kitchen_franka
action_dim: 9
robotic_joint_dims: 9
obs_dim: 30
camera_names: ['angle']
max_reward: 4
max_episode_steps: 1000
time_limit: 1000
show_episode: True
xml_path: "/home/haowen/hw_RL_code/hw_kitchen/kitchen_panda/adept_envs/franka/assets/franka_kitchen_jntpos_act_ab.xml"
step_time: 40
DT: 0.08
episode_task: ['bottom_burner', 'top_burner', 'light_switch', 'slide_cabinet', 'hinge_cabinet', 'microwave', 'kettle']
# start_arm_pose: [ 0.08228624, -1.76192224,  1.90784073, -2.48633218,  0.2495297 , 0.77931088,  1.72388411,  0.04192284,  0.03091825]
start_arm_pose: [-1.03190839, -1.7724148,   1.85066068, -1.60317659, -0.56895769,  1.27451515,  2.30460405,  0.0339087,   0.03126218]
#subtask rewritting params
goal_tgdm_kitchen_panda:
  dataset_dir: "../data/kitchen_all_data/"
  episode_len: 300
  num_episodes: 601
  num_queries: 20 #250
  WANDB_PROJECT_NAME: 'spirl_RL'
  exp_name: 'kitchen_panda_act'
  env_dim: 30
  skip_data: null
  load_all_episode: true
  num_rollouts: 5
  num_epochs: 20000
kitchen_one_task:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "begin to microwave.csv"
  episode_len: 20
  num_episodes: 300
  num_queries: 20
  WANDB_PROJECT_NAME: 'imitation_act_model'
  exp_name: 'kitchen_panda_act_one_task'
kitchen_all_task:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "microwave_kettle_bottom_burner_3.csv"
  episode_len: 200
  num_episodes: 30
  num_queries: 50
  WANDB_PROJECT_NAME: 'imitation_act_model_all_task'
  exp_name: 'kitchen_panda_act_all_task'
kitchen_one_task_allstep:
  dataset_dir: "../data/imitation/kitchen/"
  dataset_name: "microwave_data.pkl"
  episode_len: 800
  num_episodes: 300
  num_queries: 200
  WANDB_PROJECT_NAME: 'imitation_act_model_all_step'
  exp_name: 'kitchen_panda_act_all_step'
  env_dim: 30
act_example:
  use_image: true
  use_state: false
  dataset_dir: "../data/imitation/example/"
  dataset_name: "sim_transfer_cube_scripted"
  action_dim: 14
  joint_dim: 14
  episode_len: 400
  num_episodes: 50
  WANDB_PROJECT_NAME: 'imitation_act_example'
  exp_name: 'demo_sim_transfer_cube_scripted'